name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo build --release

      - name: Rename binary
        run: |
          mkdir output
          copy target\release\Fast_File_Searcher.exe output\Fast_File_Searcher-windows.exe

      - uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: output/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./windows

      - uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./windows/*
